# Build Angular apps using Azure Pipelines
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
# Specify the ode version you need for your app here
  inputs:
    versionSpec: '10.x'

- task: knom.regexreplace-task.regex-replace.RegexReplace@3
  displayName: 'RegEx Find & Replace'
  inputs:
    InputSearchPattern: '.\src\app\services\auth0-congif.ts'

    FindRegex: clientIDValue

    ReplaceRegex: '$(clientIDValue)'

- task: knom.regexreplace-task.regex-replace.RegexReplace@3
  displayName: 'RegEx Find & Replace'
  inputs:
    InputSearchPattern: '.\src\app\services\auth0-congif.ts'

    FindRegex: domainValue

    ReplaceRegex: '$(domainValue)'

- task: knom.regexreplace-task.regex-replace.RegexReplace@3
  displayName: 'RegEx Find & Replace'
  inputs:
    InputSearchPattern: '.\src\app\services\auth0-congif.ts'

    FindRegex: callbackURLValue

    ReplaceRegex: '$(callbackURLValue)'

- script: |
    npm install
    npm install -g @angular/cli
    ng build --prod 

# Zip build folder up to prepare for azure web app deployment
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: 'dist/angular-starter'
    includeRootFolder: false

#  Deploy archived folder
- task: AzureRmWebAppDeployment@3
  displayName: 'Azure WebApp Deployment'
  inputs:
    azureSubscription: $(azureSubscription)
    WebAppName: $(webAppName)
    Package: $(System.ArtifactsDirectory)/**/*.zip
