# Build Angular apps using Azure Pipelines
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
# Specify the ode version you need for your app here
  inputs:
    versionSpec: '10.x'
  
- script: |
    npm install
    npm install -g @angular/cli
    sed -i 's/clientIDValue/$(clientIDValue)/g' src/app/services/auth0-congif.ts
    sed -i 's/domainValue/$(domainValue)/g' src/app/services/auth0-congif.ts
    sed -i 's/callbackURLValue/$(callbackURLValue)/g' src/app/services/auth0-congif.ts
    ng build --prod 

# Zip build folder up to prepare for azure web app deployment
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: 'dist/angular-starter'
    includeRootFolder: false

#  Deploy archived folder
- task: AzureRmWebAppDeployment@3
  displayName: 'Azure WebApp Deployment'
  inputs:
    azureSubscription: $(azureSubscription)
    WebAppName: $(webAppName)
    Package: $(System.ArtifactsDirectory)/**/*.zip
